{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetName | quote }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    app.kubernetes.io/name: fraud-platform
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: fraud-detection-lakehouse
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ .Values.externalSecrets.targetName | quote }}
    creationPolicy: Owner
  data:
{{- range $secretKey, $remoteKey := .Values.externalSecrets.data }}
    - secretKey: {{ $secretKey | quote }}
      remoteRef:
        key: {{ $remoteKey | quote }}
{{- end }}
{{- end }}
