apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spark.serviceAccount }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    app.kubernetes.io/name: fraud-platform
    app.kubernetes.io/component: spark-driver
    app.kubernetes.io/part-of: fraud-detection-lakehouse
  annotations:
{{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
