storage_profiles:
  local:
    fileio_impl: org.apache.iceberg.aws.s3.S3FileIO
    scheme: s3
    endpoint: http://rustfs:9000
    catalog: polaris
  aws:
    fileio_impl: org.apache.iceberg.aws.s3.S3FileIO
    scheme: s3
    endpoint: ""
    catalog: polaris
    authentication: eks_pod_identity
  azure:
    fileio_impl: org.apache.iceberg.azure.adlsv2.ADLSFileIO
    scheme: abfss
    endpoint: ""
    catalog: polaris
    authentication: aks_workload_identity
  gcp:
    fileio_impl: org.apache.iceberg.gcp.gcs.GCSFileIO
    scheme: gs
    endpoint: ""
    catalog: polaris
    authentication: gke_workload_identity_federation
