connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=${ENV:POLARIS_URI}
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=${ENV:POLARIS_CREDENTIAL}
iceberg.rest-catalog.oauth2.scope=${ENV:POLARIS_SCOPE}
iceberg.rest-catalog.oauth2.server-uri=${ENV:POLARIS_TOKEN_URI}
iceberg.rest-catalog.warehouse=${ENV:POLARIS_WAREHOUSE}
iceberg.rest-catalog.vended-credentials-enabled=false
iceberg.rest-catalog.http-headers=Polaris-Realm: ${ENV:POLARIS_REALM}
fs.native-s3.enabled=true
s3.endpoint=${ENV:S3_ENDPOINT}
s3.path-style-access=true
s3.region=${ENV:S3_REGION}
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
